using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class CltTab
    {
        public string F1148 { get; set; }
        public string F902 { get; set; }
        public string F1000 { get; set; }
        public int? F1001 { get; set; }
        public string F1150 { get; set; }
        public int? F1152 { get; set; }
        public int? F1153 { get; set; }
        public string F1154 { get; set; }
        public string F1172 { get; set; }
        public string F1573 { get; set; }
        public DateTime? F253 { get; set; }
        public int? F940 { get; set; }
        public int? F941 { get; set; }
        public string F1149 { get; set; }
        public string F1151 { get; set; }
        public string F1155 { get; set; }
        public string F1156 { get; set; }
        public string F1157 { get; set; }
        public string F1158 { get; set; }
        public string F1159 { get; set; }
        public string F1160 { get; set; }
        public string F1161 { get; set; }
        public int? F1168 { get; set; }
        public string F1170 { get; set; }
        public string F1171 { get; set; }
        public string F1173 { get; set; }
        public DateTime? F1264 { get; set; }
        public DateTime? F1265 { get; set; }
        public string F1501 { get; set; }
        public string F1502 { get; set; }
        public string F1504 { get; set; }
        public DateTime? F1520 { get; set; }
        public DateTime? F1521 { get; set; }
        public DateTime? F1522 { get; set; }
        public string F1523 { get; set; }
        public string F1524 { get; set; }
        public string F1525 { get; set; }
        public DateTime? F1526 { get; set; }
        public string F1527 { get; set; }
        public string F1528 { get; set; }
        public string F1529 { get; set; }
        public string F1550 { get; set; }
        public string F1574 { get; set; }
        public DateTime? F1575 { get; set; }
        public string F1576 { get; set; }
        public string F1581 { get; set; }
        public string F1582 { get; set; }
        public DateTime? F1583 { get; set; }
        public DateTime? F1584 { get; set; }
        public string F1642 { get; set; }
        public string F1643 { get; set; }
        public string F1644 { get; set; }
        public string F1645 { get; set; }
        public string F1646 { get; set; }
        public string F1647 { get; set; }
        public string F1648 { get; set; }
        public string F1649 { get; set; }
        public string F1650 { get; set; }
        public string F1651 { get; set; }
        public double? F1654 { get; set; }
        public double? F1655 { get; set; }
        public int? F1685 { get; set; }
        public string F1692 { get; set; }
        public string F1697 { get; set; }
        public int? F1743 { get; set; }
        public int? F1759 { get; set; }
        public string F1777 { get; set; }
        public string F1778 { get; set; }
        public string F1809 { get; set; }
        public int? F1810 { get; set; }
        public string F1950 { get; set; }
        public string F1957 { get; set; }
        public string F1964 { get; set; }
        public string F2597 { get; set; }
        public string F2602 { get; set; }
        public string F2615 { get; set; }
        public int? F2616 { get; set; }
        public decimal? F2617 { get; set; }
        public double? F2619 { get; set; }
        public string F2660 { get; set; }
        public string F2743 { get; set; }
        public double? F2807 { get; set; }
        public decimal? F2808 { get; set; }
        public double? F2809 { get; set; }
        public decimal? F2810 { get; set; }
        public double? F2811 { get; set; }
        public decimal? F2812 { get; set; }
        public string F2875 { get; set; }
        public string F2889 { get; set; }
        public string F2899 { get; set; }
        public string F2900 { get; set; }
        public DateTime? F2901 { get; set; }
        public string F2904 { get; set; }
        public string F2934 { get; set; }
        public string F2977 { get; set; }
        public string F2978 { get; set; }
    }
}
