using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class CostDel
    {
        public string F01 { get; set; }
        public string F1000 { get; set; }
        public string F27 { get; set; }
        public string F1184 { get; set; }
        public string F26 { get; set; }
        public string F902 { get; set; }
        public int? F1001 { get; set; }
        public int? F07 { get; set; }
        public string F08 { get; set; }
        public double? F19 { get; set; }
        public double? F20 { get; set; }
        public string F28 { get; set; }
        public decimal? F38 { get; set; }
        public DateTime? F39 { get; set; }
        public string F90 { get; set; }
        public decimal? F120 { get; set; }
        public string F127 { get; set; }
        public int? F131 { get; set; }
        public DateTime? F134 { get; set; }
        public decimal? F151 { get; set; }
        public DateTime? F152 { get; set; }
        public string F156 { get; set; }
        public string F165 { get; set; }
        public decimal? F185 { get; set; }
        public double? F194 { get; set; }
        public decimal? F195 { get; set; }
        public decimal? F196 { get; set; }
        public decimal? F201 { get; set; }
        public DateTime? F202 { get; set; }
        public DateTime? F203 { get; set; }
        public string F204 { get; set; }
        public string F212 { get; set; }
        public DateTime? F216 { get; set; }
        public DateTime? F219 { get; set; }
        public string F220 { get; set; }
        public string F222 { get; set; }
        public string F223 { get; set; }
        public double? F224 { get; set; }
        public decimal? F225 { get; set; }
        public double? F226 { get; set; }
        public DateTime? F227 { get; set; }
        public double? F228 { get; set; }
        public DateTime? F229 { get; set; }
        public DateTime? F230 { get; set; }
        public string F231 { get; set; }
        public decimal? F233 { get; set; }
        public DateTime? F234 { get; set; }
        public DateTime? F235 { get; set; }
        public string F236 { get; set; }
        public double? F237 { get; set; }
        public DateTime? F253 { get; set; }
        public double? F325 { get; set; }
        public double? F326 { get; set; }
        public double? F327 { get; set; }
        public double? F328 { get; set; }
        public double? F329 { get; set; }
        public string F1037 { get; set; }
        public string F1038 { get; set; }
        public decimal? F1121 { get; set; }
        public double? F1122 { get; set; }
        public decimal? F1140 { get; set; }
        public int? F1168 { get; set; }
        public double? F1657 { get; set; }
        public decimal? F1658 { get; set; }
        public string F1659 { get; set; }
        public string F1660 { get; set; }
        public string F1661 { get; set; }
        public decimal? F1662 { get; set; }
        public double? F1663 { get; set; }
        public decimal? F1664 { get; set; }
        public double? F1665 { get; set; }
        public decimal? F1666 { get; set; }
        public double? F1667 { get; set; }
        public string F1668 { get; set; }
        public decimal? F1669 { get; set; }
        public double? F1670 { get; set; }
        public int? F1685 { get; set; }
        public int? F1759 { get; set; }
        public double? F1760 { get; set; }
        public double? F1761 { get; set; }
        public decimal? F1766 { get; set; }
        public string F1791 { get; set; }
        public string F1792 { get; set; }
        public int? F1793 { get; set; }
        public int? F1794 { get; set; }
        public double? F1795 { get; set; }
        public double? F1796 { get; set; }
        public decimal? F1797 { get; set; }
        public decimal? F1798 { get; set; }
        public string F1875 { get; set; }
        public string F1887 { get; set; }
        public string F1961 { get; set; }
        public string F1964 { get; set; }
        public string F1973 { get; set; }
        public string F1974 { get; set; }
        public string F1975 { get; set; }
        public string F1976 { get; set; }
        public double? F1977 { get; set; }
        public double? F1978 { get; set; }
        public double? F1979 { get; set; }
        public string F2119 { get; set; }
        public double? F2566 { get; set; }
        public double? F2567 { get; set; }
        public double? F2568 { get; set; }
        public string F2601 { get; set; }
        public int? F2624 { get; set; }
        public decimal? F2626 { get; set; }
        public double? F2628 { get; set; }
        public double? F2666 { get; set; }
        public DateTime? F2699 { get; set; }
    }
}
