using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class OposBat
    {
        public string F01 { get; set; }
        public string F902 { get; set; }
        public string F1000 { get; set; }
        public string F02 { get; set; }
        public int? F03 { get; set; }
        public int? F04 { get; set; }
        public int? F05 { get; set; }
        public int? F06 { get; set; }
        public int? F07 { get; set; }
        public string F08 { get; set; }
        public DateTime? F09 { get; set; }
        public double? F24 { get; set; }
        public string F40 { get; set; }
        public decimal? F50 { get; set; }
        public decimal? F60 { get; set; }
        public decimal? F61 { get; set; }
        public int? F66 { get; set; }
        public int? F77 { get; set; }
        public string F78 { get; set; }
        public string F79 { get; set; }
        public string F80 { get; set; }
        public string F81 { get; set; }
        public string F82 { get; set; }
        public string F83 { get; set; }
        public string F84 { get; set; }
        public string F85 { get; set; }
        public string F86 { get; set; }
        public string F87 { get; set; }
        public string F88 { get; set; }
        public string F92 { get; set; }
        public string F96 { get; set; }
        public string F97 { get; set; }
        public string F98 { get; set; }
        public string F99 { get; set; }
        public string F100 { get; set; }
        public string F101 { get; set; }
        public string F102 { get; set; }
        public string F104 { get; set; }
        public string F106 { get; set; }
        public string F107 { get; set; }
        public string F108 { get; set; }
        public string F110 { get; set; }
        public string F114 { get; set; }
        public string F115 { get; set; }
        public string F121 { get; set; }
        public string F123 { get; set; }
        public string F124 { get; set; }
        public string F125 { get; set; }
        public double? F141 { get; set; }
        public string F149 { get; set; }
        public string F150 { get; set; }
        public int? F153 { get; set; }
        public string F158 { get; set; }
        public string F159 { get; set; }
        public string F160 { get; set; }
        public string F161 { get; set; }
        public string F162 { get; set; }
        public int? F163 { get; set; }
        public int? F170 { get; set; }
        public int? F171 { get; set; }
        public string F172 { get; set; }
        public string F173 { get; set; }
        public string F174 { get; set; }
        public string F176 { get; set; }
        public string F178 { get; set; }
        public string F188 { get; set; }
        public string F189 { get; set; }
        public double? F209 { get; set; }
        public decimal? F210 { get; set; }
        public DateTime? F211 { get; set; }
        public double? F217 { get; set; }
        public string F302 { get; set; }
        public DateTime? F303 { get; set; }
        public string F304 { get; set; }
        public double? F306 { get; set; }
        public string F383 { get; set; }
        public string F388 { get; set; }
        public string F397 { get; set; }
        public int? F1001 { get; set; }
        public int? F1099 { get; set; }
        public string F1120 { get; set; }
        public double? F1124 { get; set; }
        public string F1136 { get; set; }
        public double? F1138 { get; set; }
        public int? F1139 { get; set; }
        public string F1236 { get; set; }
        public double? F1237 { get; set; }
        public string F1735 { get; set; }
        public string F1785 { get; set; }
        public string F1786 { get; set; }
        public int? F1787 { get; set; }
        public int? F1788 { get; set; }
        public double? F1789 { get; set; }
        public double? F1790 { get; set; }
        public string F1892 { get; set; }
        public double? F1926 { get; set; }
        public int? F1929 { get; set; }
        public decimal? F1933 { get; set; }
        public string F1964 { get; set; }
        public string F2608 { get; set; }
        public string F2660 { get; set; }
        public string F2930 { get; set; }
    }
}
