using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class PriceTab
    {
        public string F01 { get; set; }
        public string F1000 { get; set; }
        public int F126 { get; set; }
        public int? F32 { get; set; }
        public string F902 { get; set; }
        public int? F1001 { get; set; }
        public DateTime? F1014 { get; set; }
        public int? F07 { get; set; }
        public double? F21 { get; set; }
        public decimal? F30 { get; set; }
        public double? F31 { get; set; }
        public string F33 { get; set; }
        public string F34 { get; set; }
        public DateTime? F35 { get; set; }
        public string F36 { get; set; }
        public string F37 { get; set; }
        public string F41 { get; set; }
        public string F42 { get; set; }
        public string F43 { get; set; }
        public double? F49 { get; set; }
        public string F59 { get; set; }
        public double? F62 { get; set; }
        public decimal? F63 { get; set; }
        public string F109 { get; set; }
        public decimal? F111 { get; set; }
        public double? F112 { get; set; }
        public string F113 { get; set; }
        public string F119 { get; set; }
        public string F122 { get; set; }
        public DateTime? F129 { get; set; }
        public string F130 { get; set; }
        public DateTime? F133 { get; set; }
        public double? F135 { get; set; }
        public decimal? F136 { get; set; }
        public DateTime? F137 { get; set; }
        public DateTime? F138 { get; set; }
        public decimal? F139 { get; set; }
        public decimal? F140 { get; set; }
        public double? F142 { get; set; }
        public double? F143 { get; set; }
        public string F144 { get; set; }
        public string F145 { get; set; }
        public string F146 { get; set; }
        public double? F147 { get; set; }
        public decimal? F148 { get; set; }
        public string F164 { get; set; }
        public decimal? F166 { get; set; }
        public double? F167 { get; set; }
        public decimal? F168 { get; set; }
        public int? F169 { get; set; }
        public string F175 { get; set; }
        public string F177 { get; set; }
        public string F179 { get; set; }
        public decimal? F181 { get; set; }
        public double? F182 { get; set; }
        public DateTime? F183 { get; set; }
        public DateTime? F184 { get; set; }
        public decimal? F205 { get; set; }
        public string F221 { get; set; }
        public double? F232 { get; set; }
        public DateTime? F253 { get; set; }
        public string F903 { get; set; }
        public string F1005 { get; set; }
        public double? F1006 { get; set; }
        public decimal? F1007 { get; set; }
        public DateTime? F1008 { get; set; }
        public string F1009 { get; set; }
        public string F1010 { get; set; }
        public string F1011 { get; set; }
        public double? F1012 { get; set; }
        public decimal? F1013 { get; set; }
        public string F1015 { get; set; }
        public decimal? F1133 { get; set; }
        public double? F1134 { get; set; }
        public string F1135 { get; set; }
        public decimal? F1186 { get; set; }
        public double? F1187 { get; set; }
        public decimal? F1188 { get; set; }
        public double? F1189 { get; set; }
        public int? F1190 { get; set; }
        public int? F1191 { get; set; }
        public int? F1192 { get; set; }
        public int? F1193 { get; set; }
        public string F1194 { get; set; }
        public string F1195 { get; set; }
        public decimal? F1196 { get; set; }
        public double? F1197 { get; set; }
        public decimal? F1198 { get; set; }
        public double? F1199 { get; set; }
        public int? F1200 { get; set; }
        public string F1201 { get; set; }
        public int? F1202 { get; set; }
        public decimal? F1203 { get; set; }
        public double? F1204 { get; set; }
        public decimal? F1205 { get; set; }
        public double? F1206 { get; set; }
        public int? F1207 { get; set; }
        public string F1208 { get; set; }
        public int? F1209 { get; set; }
        public decimal? F1210 { get; set; }
        public double? F1211 { get; set; }
        public decimal? F1212 { get; set; }
        public double? F1213 { get; set; }
        public int? F1214 { get; set; }
        public int? F1215 { get; set; }
        public DateTime? F1216 { get; set; }
        public DateTime? F1217 { get; set; }
        public decimal? F1218 { get; set; }
        public double? F1219 { get; set; }
        public decimal? F1220 { get; set; }
        public double? F1221 { get; set; }
        public decimal? F1222 { get; set; }
        public double? F1223 { get; set; }
        public decimal? F1224 { get; set; }
        public double? F1225 { get; set; }
        public decimal? F1226 { get; set; }
        public double? F1227 { get; set; }
        public int? F1228 { get; set; }
        public decimal? F1229 { get; set; }
        public int? F1230 { get; set; }
        public decimal? F1231 { get; set; }
        public int? F1232 { get; set; }
        public decimal? F1233 { get; set; }
        public DateTime? F1234 { get; set; }
        public DateTime? F1235 { get; set; }
        public double? F1713 { get; set; }
        public string F1714 { get; set; }
        public int? F1759 { get; set; }
        public double? F1767 { get; set; }
        public string F1768 { get; set; }
        public double? F1769 { get; set; }
        public string F1770 { get; set; }
        public string F1799 { get; set; }
        public string F1800 { get; set; }
        public int? F1801 { get; set; }
        public int? F1802 { get; set; }
        public double? F1803 { get; set; }
        public double? F1804 { get; set; }
        public decimal? F1805 { get; set; }
        public decimal? F1806 { get; set; }
        public decimal? F1885 { get; set; }
        public double? F1927 { get; set; }
        public double? F1928 { get; set; }
        public int? F1930 { get; set; }
        public decimal? F1934 { get; set; }
        public decimal? F1935 { get; set; }
        public string F1964 { get; set; }
        public string F2119 { get; set; }
        public string F2569 { get; set; }
        public double? F2570 { get; set; }
        public decimal? F2571 { get; set; }
        public double? F2572 { get; set; }
        public decimal? F2573 { get; set; }
        public double? F2574 { get; set; }
        public int? F2575 { get; set; }
        public int? F2576 { get; set; }
        public decimal? F2577 { get; set; }
        public double? F2578 { get; set; }
        public string F2579 { get; set; }
        public int? F2580 { get; set; }
        public string F2667 { get; set; }
        public string F2668 { get; set; }
        public string F2694 { get; set; }
        public string F2695 { get; set; }
        public string F2696 { get; set; }
        public string F2744 { get; set; }
        public double? F2955 { get; set; }
    }
}
