using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class RecReg
    {
        public int F1032 { get; set; }
        public int F1101 { get; set; }
        public string F01 { get; set; }
        public int? F03 { get; set; }
        public int? F04 { get; set; }
        public int? F05 { get; set; }
        public string F08 { get; set; }
        public double? F19 { get; set; }
        public double? F20 { get; set; }
        public string F26 { get; set; }
        public decimal? F38 { get; set; }
        public decimal? F50 { get; set; }
        public double? F64 { get; set; }
        public decimal? F65 { get; set; }
        public double? F67 { get; set; }
        public double? F70 { get; set; }
        public double? F75 { get; set; }
        public DateTime? F76 { get; set; }
        public string F81 { get; set; }
        public string F82 { get; set; }
        public string F90 { get; set; }
        public string F92 { get; set; }
        public string F96 { get; set; }
        public string F97 { get; set; }
        public string F98 { get; set; }
        public string F99 { get; set; }
        public string F100 { get; set; }
        public string F101 { get; set; }
        public decimal? F120 { get; set; }
        public int? F131 { get; set; }
        public decimal? F151 { get; set; }
        public string F156 { get; set; }
        public decimal? F186 { get; set; }
        public decimal? F201 { get; set; }
        public DateTime? F202 { get; set; }
        public DateTime? F203 { get; set; }
        public string F204 { get; set; }
        public DateTime? F219 { get; set; }
        public string F220 { get; set; }
        public string F222 { get; set; }
        public string F223 { get; set; }
        public double? F224 { get; set; }
        public decimal? F225 { get; set; }
        public double? F226 { get; set; }
        public DateTime? F227 { get; set; }
        public double? F228 { get; set; }
        public DateTime? F229 { get; set; }
        public DateTime? F230 { get; set; }
        public string F231 { get; set; }
        public decimal? F233 { get; set; }
        public DateTime? F234 { get; set; }
        public DateTime? F235 { get; set; }
        public string F236 { get; set; }
        public double? F237 { get; set; }
        public DateTime? F253 { get; set; }
        public DateTime? F254 { get; set; }
        public double? F270 { get; set; }
        public double? F327 { get; set; }
        public double? F328 { get; set; }
        public double? F329 { get; set; }
        public double? F1003 { get; set; }
        public int? F1034 { get; set; }
        public string F1041 { get; set; }
        public int? F1063 { get; set; }
        public string F1067 { get; set; }
        public string F1069 { get; set; }
        public string F1070 { get; set; }
        public string F1071 { get; set; }
        public string F1079 { get; set; }
        public string F1081 { get; set; }
        public string F1086 { get; set; }
        public decimal? F1121 { get; set; }
        public double? F1122 { get; set; }
        public decimal? F1140 { get; set; }
        public string F1184 { get; set; }
        public DateTime? F1246 { get; set; }
        public string F1247 { get; set; }
        public string F1248 { get; set; }
        public decimal? F1249 { get; set; }
        public decimal? F1250 { get; set; }
        public decimal? F1251 { get; set; }
        public decimal? F1252 { get; set; }
        public double? F1266 { get; set; }
        public double? F1267 { get; set; }
        public decimal? F1595 { get; set; }
        public int? F1596 { get; set; }
        public double? F1657 { get; set; }
        public decimal? F1658 { get; set; }
        public string F1659 { get; set; }
        public string F1660 { get; set; }
        public string F1661 { get; set; }
        public decimal? F1662 { get; set; }
        public double? F1663 { get; set; }
        public decimal? F1664 { get; set; }
        public double? F1665 { get; set; }
        public decimal? F1666 { get; set; }
        public double? F1667 { get; set; }
        public string F1668 { get; set; }
        public decimal? F1669 { get; set; }
        public double? F1670 { get; set; }
        public decimal? F1671 { get; set; }
        public decimal? F1672 { get; set; }
        public decimal? F1673 { get; set; }
        public decimal? F1674 { get; set; }
        public string F1675 { get; set; }
        public decimal? F1676 { get; set; }
        public string F1677 { get; set; }
        public decimal? F1678 { get; set; }
        public int? F1679 { get; set; }
        public DateTime? F1680 { get; set; }
        public decimal? F1681 { get; set; }
        public decimal? F1682 { get; set; }
        public double? F1683 { get; set; }
        public double? F1684 { get; set; }
        public int? F1685 { get; set; }
        public int? F1687 { get; set; }
        public string F1691 { get; set; }
        public double? F1732 { get; set; }
        public decimal? F1771 { get; set; }
        public decimal? F1772 { get; set; }
        public decimal? F1773 { get; set; }
        public decimal? F1774 { get; set; }
        public decimal? F1775 { get; set; }
        public int? F1776 { get; set; }
        public string F1791 { get; set; }
        public int? F1793 { get; set; }
        public double? F1795 { get; set; }
        public decimal? F1797 { get; set; }
        public decimal? F1815 { get; set; }
        public int? F1816 { get; set; }
        public string F1887 { get; set; }
        public decimal? F1899 { get; set; }
        public double? F1918 { get; set; }
        public double? F1919 { get; set; }
        public double? F1920 { get; set; }
        public string F1973 { get; set; }
        public string F1974 { get; set; }
        public string F1975 { get; set; }
        public string F1976 { get; set; }
        public double? F1977 { get; set; }
        public double? F1978 { get; set; }
        public double? F1979 { get; set; }
        public decimal? F2551 { get; set; }
        public decimal? F2552 { get; set; }
        public decimal? F2553 { get; set; }
        public decimal? F2554 { get; set; }
        public decimal? F2555 { get; set; }
        public decimal? F2556 { get; set; }
        public decimal? F2557 { get; set; }
        public decimal? F2558 { get; set; }
        public decimal? F2559 { get; set; }
        public decimal? F2560 { get; set; }
        public decimal? F2561 { get; set; }
        public decimal? F2562 { get; set; }
        public decimal? F2563 { get; set; }
        public decimal? F2564 { get; set; }
        public decimal? F2565 { get; set; }
        public double? F2566 { get; set; }
        public double? F2567 { get; set; }
        public double? F2568 { get; set; }
        public int? F2624 { get; set; }
        public int? F2625 { get; set; }
        public decimal? F2626 { get; set; }
        public decimal? F2627 { get; set; }
        public double? F2628 { get; set; }
        public double? F2629 { get; set; }
        public string F2630 { get; set; }
        public int? F2631 { get; set; }
        public string F2660 { get; set; }
        public double? F2666 { get; set; }
        public decimal? F2709 { get; set; }
        public decimal? F2711 { get; set; }
        public decimal? F2712 { get; set; }
        public decimal? F2713 { get; set; }
        public decimal? F2714 { get; set; }
        public decimal? F2715 { get; set; }
        public decimal? F2716 { get; set; }
        public decimal? F2717 { get; set; }
        public decimal? F2718 { get; set; }
        public double? F2864 { get; set; }
        public double? F2868 { get; set; }
        public decimal? F2872 { get; set; }
        public decimal? F2873 { get; set; }
    }
}
