using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class SalHdr
    {
        public int F1032 { get; set; }
        public string F1148 { get; set; }
        public DateTime? F76 { get; set; }
        public string F91 { get; set; }
        public DateTime? F253 { get; set; }
        public DateTime? F254 { get; set; }
        public string F902 { get; set; }
        public string F1035 { get; set; }
        public string F1036 { get; set; }
        public string F1056 { get; set; }
        public string F1057 { get; set; }
        public string F1067 { get; set; }
        public string F1068 { get; set; }
        public int? F1101 { get; set; }
        public int? F1126 { get; set; }
        public string F1127 { get; set; }
        public int? F1137 { get; set; }
        public string F1149 { get; set; }
        public string F1150 { get; set; }
        public string F1151 { get; set; }
        public int? F1152 { get; set; }
        public int? F1153 { get; set; }
        public string F1154 { get; set; }
        public string F1155 { get; set; }
        public string F1156 { get; set; }
        public string F1157 { get; set; }
        public string F1158 { get; set; }
        public string F1159 { get; set; }
        public string F1160 { get; set; }
        public string F1161 { get; set; }
        public int? F1163 { get; set; }
        public double? F1164 { get; set; }
        public decimal? F1165 { get; set; }
        public string F1167 { get; set; }
        public int? F1168 { get; set; }
        public string F1170 { get; set; }
        public string F1171 { get; set; }
        public string F1172 { get; set; }
        public string F1173 { get; set; }
        public int? F1185 { get; set; }
        public int? F1238 { get; set; }
        public decimal? F1242 { get; set; }
        public string F1245 { get; set; }
        public DateTime? F1246 { get; set; }
        public string F1254 { get; set; }
        public string F1255 { get; set; }
        public string F1271 { get; set; }
        public string F1272 { get; set; }
        public string F1273 { get; set; }
        public string F1274 { get; set; }
        public string F1277 { get; set; }
        public string F1287 { get; set; }
        public string F1288 { get; set; }
        public string F1295 { get; set; }
        public string F1504 { get; set; }
        public DateTime? F1520 { get; set; }
        public string F1573 { get; set; }
        public string F1642 { get; set; }
        public string F1643 { get; set; }
        public string F1644 { get; set; }
        public string F1645 { get; set; }
        public string F1646 { get; set; }
        public string F1647 { get; set; }
        public string F1648 { get; set; }
        public string F1649 { get; set; }
        public string F1650 { get; set; }
        public string F1651 { get; set; }
        public string F1652 { get; set; }
        public DateTime? F1653 { get; set; }
        public double? F1654 { get; set; }
        public double? F1655 { get; set; }
        public int? F1685 { get; set; }
        public int? F1686 { get; set; }
        public int? F1687 { get; set; }
        public int? F1688 { get; set; }
        public int? F1689 { get; set; }
        public string F1692 { get; set; }
        public int? F1693 { get; set; }
        public int? F1694 { get; set; }
        public int? F1695 { get; set; }
        public int? F1696 { get; set; }
        public string F1697 { get; set; }
        public double? F1699 { get; set; }
        public int? F1711 { get; set; }
        public string F1763 { get; set; }
        public string F1764 { get; set; }
        public double? F1938 { get; set; }
        public DateTime? F2596 { get; set; }
        public double? F2598 { get; set; }
        public double? F2599 { get; set; }
        public int? F2613 { get; set; }
        public decimal? F2614 { get; set; }
        public string F2615 { get; set; }
        public int? F2616 { get; set; }
        public decimal? F2617 { get; set; }
        public decimal? F2618 { get; set; }
        public double? F2619 { get; set; }
        public double? F2620 { get; set; }
        public int? F2621 { get; set; }
        public int? F2622 { get; set; }
        public string F2623 { get; set; }
        public string F2816 { get; set; }
        public string F2848 { get; set; }
        public string F2889 { get; set; }
        public string F2904 { get; set; }
        public string F2934 { get; set; }
    }
}
