using System;
using System.Collections.Generic;

namespace Storeman.Models
{
    public partial class SalReg
    {
        public int F1032 { get; set; }
        public int F1101 { get; set; }
        public string F01 { get; set; }
        public int? F03 { get; set; }
        public int? F04 { get; set; }
        public int? F05 { get; set; }
        public int? F06 { get; set; }
        public string F08 { get; set; }
        public double? F24 { get; set; }
        public decimal? F30 { get; set; }
        public double? F31 { get; set; }
        public string F43 { get; set; }
        public decimal? F50 { get; set; }
        public decimal? F60 { get; set; }
        public decimal? F61 { get; set; }
        public double? F64 { get; set; }
        public decimal? F65 { get; set; }
        public double? F67 { get; set; }
        public int? F77 { get; set; }
        public string F79 { get; set; }
        public string F80 { get; set; }
        public string F81 { get; set; }
        public string F82 { get; set; }
        public string F83 { get; set; }
        public string F88 { get; set; }
        public string F96 { get; set; }
        public string F97 { get; set; }
        public string F98 { get; set; }
        public string F99 { get; set; }
        public string F100 { get; set; }
        public string F101 { get; set; }
        public string F102 { get; set; }
        public string F104 { get; set; }
        public string F106 { get; set; }
        public string F108 { get; set; }
        public string F109 { get; set; }
        public string F110 { get; set; }
        public string F113 { get; set; }
        public string F114 { get; set; }
        public string F115 { get; set; }
        public string F117 { get; set; }
        public string F124 { get; set; }
        public string F125 { get; set; }
        public int? F126 { get; set; }
        public string F149 { get; set; }
        public string F150 { get; set; }
        public string F160 { get; set; }
        public int? F163 { get; set; }
        public decimal? F168 { get; set; }
        public int? F169 { get; set; }
        public int? F170 { get; set; }
        public int? F171 { get; set; }
        public string F172 { get; set; }
        public string F173 { get; set; }
        public string F175 { get; set; }
        public string F177 { get; set; }
        public string F178 { get; set; }
        public DateTime? F253 { get; set; }
        public DateTime? F254 { get; set; }
        public double? F270 { get; set; }
        public string F383 { get; set; }
        public string F903 { get; set; }
        public double? F1002 { get; set; }
        public double? F1006 { get; set; }
        public decimal? F1007 { get; set; }
        public int? F1034 { get; set; }
        public string F1041 { get; set; }
        public int? F1063 { get; set; }
        public string F1067 { get; set; }
        public string F1069 { get; set; }
        public string F1070 { get; set; }
        public string F1071 { get; set; }
        public int? F1072 { get; set; }
        public double? F1078 { get; set; }
        public string F1079 { get; set; }
        public double? F1080 { get; set; }
        public string F1081 { get; set; }
        public string F1086 { get; set; }
        public string F1120 { get; set; }
        public int? F1126 { get; set; }
        public string F1136 { get; set; }
        public double? F1164 { get; set; }
        public double? F1178 { get; set; }
        public int? F1185 { get; set; }
        public decimal? F1203 { get; set; }
        public double? F1204 { get; set; }
        public decimal? F1205 { get; set; }
        public double? F1206 { get; set; }
        public int? F1207 { get; set; }
        public string F1208 { get; set; }
        public int? F1209 { get; set; }
        public decimal? F1224 { get; set; }
        public double? F1225 { get; set; }
        public int? F1239 { get; set; }
        public decimal? F1240 { get; set; }
        public decimal? F1241 { get; set; }
        public double? F1256 { get; set; }
        public decimal? F1263 { get; set; }
        public decimal? F1595 { get; set; }
        public int? F1596 { get; set; }
        public double? F1683 { get; set; }
        public double? F1684 { get; set; }
        public int? F1687 { get; set; }
        public string F1691 { get; set; }
        public int? F1693 { get; set; }
        public int? F1694 { get; set; }
        public double? F1699 { get; set; }
        public double? F1712 { get; set; }
        public decimal? F1715 { get; set; }
        public decimal? F1716 { get; set; }
        public double? F1717 { get; set; }
        public int? F1718 { get; set; }
        public decimal? F1719 { get; set; }
        public decimal? F1720 { get; set; }
        public int? F1721 { get; set; }
        public decimal? F1722 { get; set; }
        public decimal? F1723 { get; set; }
        public decimal? F1724 { get; set; }
        public double? F1725 { get; set; }
        public decimal? F1726 { get; set; }
        public decimal? F1727 { get; set; }
        public decimal? F1728 { get; set; }
        public decimal? F1729 { get; set; }
        public decimal? F1730 { get; set; }
        public int? F1731 { get; set; }
        public double? F1732 { get; set; }
        public decimal? F1733 { get; set; }
        public decimal? F1734 { get; set; }
        public double? F1739 { get; set; }
        public double? F1740 { get; set; }
        public string F1741 { get; set; }
        public string F1742 { get; set; }
        public string F1785 { get; set; }
        public int? F1787 { get; set; }
        public double? F1789 { get; set; }
        public int? F1802 { get; set; }
        public double? F1803 { get; set; }
        public decimal? F1805 { get; set; }
        public decimal? F1815 { get; set; }
        public int? F1816 { get; set; }
        public int? F1831 { get; set; }
        public int? F1832 { get; set; }
        public decimal? F1833 { get; set; }
        public decimal? F1834 { get; set; }
        public double? F1835 { get; set; }
        public int? F1860 { get; set; }
        public double? F1861 { get; set; }
        public int? F1862 { get; set; }
        public double? F1863 { get; set; }
        public double? F1864 { get; set; }
        public int? F1874 { get; set; }
        public double? F1888 { get; set; }
        public double? F1924 { get; set; }
        public double? F1925 { get; set; }
        public double? F1926 { get; set; }
        public double? F1927 { get; set; }
        public double? F1928 { get; set; }
        public int? F1929 { get; set; }
        public int? F1930 { get; set; }
        public int? F1931 { get; set; }
        public decimal? F1932 { get; set; }
        public decimal? F1933 { get; set; }
        public decimal? F1934 { get; set; }
        public decimal? F1935 { get; set; }
        public decimal? F1936 { get; set; }
        public double? F1938 { get; set; }
        public decimal? F2551 { get; set; }
        public decimal? F2552 { get; set; }
        public decimal? F2553 { get; set; }
        public decimal? F2554 { get; set; }
        public decimal? F2555 { get; set; }
        public string F2608 { get; set; }
        public int? F2609 { get; set; }
        public decimal? F2610 { get; set; }
        public decimal? F2611 { get; set; }
        public string F2612 { get; set; }
        public int? F2613 { get; set; }
        public decimal? F2614 { get; set; }
        public string F2660 { get; set; }
        public string F2744 { get; set; }
        public string F2745 { get; set; }
        public string F2746 { get; set; }
        public int? F2747 { get; set; }
        public int? F2748 { get; set; }
        public int? F2749 { get; set; }
        public int? F2750 { get; set; }
        public int? F2751 { get; set; }
        public string F2752 { get; set; }
        public string F2753 { get; set; }
        public double? F2860 { get; set; }
        public int? F2861 { get; set; }
        public int? F2862 { get; set; }
        public int? F2863 { get; set; }
        public double? F2865 { get; set; }
        public double? F2866 { get; set; }
        public double? F2867 { get; set; }
        public decimal? F2869 { get; set; }
        public decimal? F2870 { get; set; }
        public decimal? F2871 { get; set; }
    }
}
